version: '3.7'

services:
  pgdb:
    restart: always
    image: postgres
    container_name: mycrm_pgdb
    hostname: pgdb
    env_file: .env
    volumes:
    - .db:/var/lib/postgresql/data
    expose:
    - 5346
  
  pgadmin:
    restart: always
    image: dpage/pgadmin4
    container_name: mycrm_pgadmin
    hostname: pgadmin
    env_file: .env
    ports:
    - "9090:80"
    depends_on:
    - pgdb

  app:
    restart: always
    build:
      context: .
      args:
        APP_HOME: /app
    container_name: mycrm_app
    hostname: mycrm
    env_file: .env
    working_dir: /app
    ports:
    - "8080:8080"
    command: npm start
    volumes:
      - ./server:/app/server
      - ./client:/app/client
      - ./logs:/app/logs
    depends_on: 
      - pgdb